# 각 잡에 대한 기본값
default:
  interruptible: false
  image: ubuntu:latest

stages:
  - metadata
  - integration

# 각 잡 컨테이너에서 실행됨
before_script:
  - echo "job started on ${BUILD_ENV}"

# 각 잡 컨테이너에서 실행됨
after_script:
  - echo 'job finished'

job_metadata:
  image: python:3.8

  stage: metadata

  # only:
  #   - staging
  #   - branches
  # except:
  #   - master
  
  # 배포 환경 정보
  environment:
    name: target
    url: http://target.geniouslab.io

  # 실행할 스크립트 내용
  # before_script:
  # after_script:
  script:
    - echo 'job running...'
    - pwd
    - ls -al
    - python3 --version

  # 캐시 옵션
  # cache:
  #   key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  #   paths:
  #     - /tmp


job_docker_build:
  stage: integration
  image:
    name: docker.io/clownchrys/published:builder
    pull_policy: always
  variables:
    TARGET_REPOSITORY: docker.io/clownchrys/test
    TARGET_TAG: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}
  before_script:
    - env
    - /kaniko/executor version
    - cat /kaniko/.docker/config.json
  script:
    # - sleep inf
    - tree ./docker
    - if git diff HEAD~ --name-only | grep docker/;
      then
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/docker"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --destination "${TARGET_REPOSITORY}:${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}"
      ;
      fi
      # --custom-platform linux/amd64
      # --cache
      # --cache-copy-layers
      # --cache-run-layers
      # --no-push-cache
      # --no-push
  after_script: 
    - echo 'job done!'


job_volume_delivery:
  stage: integration
  before_script:
    - ls -al ./volume
  script:
    - echo 'scp ...'
  after_script: 
    - echo 'delivered OK!'


# FF_POSIXLY_CORRECT_ESCAPES=false
# GITLAB_USER_LOGIN=root
# CI_COMMIT_SHORT_SHA=a45117c0
# FF_USE_WINDOWS_LEGACY_PROCESS_STRATEGY=false
# CI_SERVER_VERSION_PATCH=3
# FF_SCRIPT_SECTIONS=false
# CI_SERVER_REVISION=94ad2c3b191
# GITLAB_PROMETHEUS_SERVER_PORT=tcp://10.96.199.210:80
# GITLAB_REDIS_METRICS_PORT_9121_TCP_ADDR=10.96.219.146
# GITLAB_POSTGRESQL_METRICS_PORT_9187_TCP_PROTO=tcp
# GITLAB_KAS_SERVICE_PORT_HTTP_METRICS=8151
# GITLAB_PROMETHEUS_SERVER_SERVICE_PORT=80
# GITLAB_KAS_PORT_8151_TCP_ADDR=10.96.191.81
# GITLAB_CERTMANAGER_WEBHOOK_SERVICE_HOST=10.96.203.90
# GITLAB_REGISTRY_SERVICE_PORT_HTTP_REGISTRY=5000
# KUBERNETES_PORT=tcp://10.96.0.1:443
# GITLAB_WEBSERVICE_DEFAULT_SERVICE_PORT_HTTP_METRICS_WS=8083
# GITLAB_KAS_SERVICE_HOST=10.96.191.81
# KUBERNETES_SERVICE_PORT=443
# GITLAB_CERTMANAGER_PORT_9402_TCP_ADDR=10.96.12.220
# USER=root
# FF_USE_DUMB_INIT_WITH_KUBERNETES_EXECUTOR=false
# GITLAB_REDIS_METRICS_SERVICE_PORT_HTTP_METRICS=9121
# GITLAB_KAS_PORT_8153_TCP_ADDR=10.96.191.81
# GITLAB_CERTMANAGER_SERVICE_HOST=10.96.12.220
# GITLAB_KAS_PORT_8150_TCP_PORT=8150
# FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY=false
# CI_RUNNER_REVISION=81ab07f6
# CI_PROJECT_NAME=fastapi
# FF_LOG_IMAGES_CONFIGURED_FOR_JOB=false
# CI=true
# CI_SERVER_PROTOCOL=http
# GITLAB_GITLAB_SHELL_PORT_22_TCP=tcp://10.96.114.103:22
# GITLAB_REDIS_METRICS_SERVICE_HOST=10.96.219.146
# GITLAB_KAS_PORT_8151_TCP_PORT=8151
# GITLAB_KAS_PORT_8154_TCP_ADDR=10.96.191.81
# GITLAB_REDIS_METRICS_PORT_9121_TCP_PORT=9121
# GITLAB_KAS_PORT_8150_TCP_PROTO=tcp
# HOSTNAME=runner-qlz4ac2y-project-2-concurrent-0-4h9dd4iv
# DOCKER_CREDENTIAL_GCR_CONFIG=/kaniko/.config/gcloud/docker_credential_gcr_config.json
# CI_PROJECT_DESCRIPTION=
# CI_COMMIT_DESCRIPTION=
# CI_JOB_STAGE=integration
# GITLAB_GITLAB_EXPORTER_SERVICE_PORT_HTTP_METRICS=9168
# GITLAB_KAS_PORT_8151_TCP_PROTO=tcp
# GITLAB_REDIS_METRICS_PORT_9121_TCP_PROTO=tcp
# GITLAB_CERTMANAGER_PORT_9402_TCP_PORT=9402
# CI_SERVER_VERSION=16.10.3
# GITLAB_CERTMANAGER_PORT_9402_TCP_PROTO=tcp
# GITLAB_KAS_PORT_8153_TCP_PORT=8153
# GITLAB_GITLAB_EXPORTER_SERVICE_HOST=10.96.236.110
# SHLVL=1
# HOME=/root
# FF_DISABLE_POWERSHELL_STDIN=false
# CI_PROJECT_ROOT_NAMESPACE=cicd
# FF_CLEAN_UP_FAILED_CACHE_EXTRACT=false
# GITLAB_KAS_PORT_8154_TCP_PORT=8154
# GITLAB_PROMETHEUS_SERVER_PORT_80_TCP_ADDR=10.96.199.210
# GITLAB_REDIS_MASTER_SERVICE_HOST=10.96.168.122
# GITLAB_KAS_PORT_8153_TCP_PROTO=tcp
# CI_JOB_ID=103
# CI_SERVER_HOST=gitlab.geniouslab.io
# FF_NETWORK_PER_BUILD=false
# CI_COMMIT_REF_NAME=main
# GITLAB_CERTMANAGER_WEBHOOK_PORT=tcp://10.96.203.90:443
# GITLAB_KAS_PORT_8154_TCP_PROTO=tcp
# GITLAB_CERTMANAGER_WEBHOOK_SERVICE_PORT=443
# GITLAB_CERTMANAGER_SERVICE_PORT_TCP_PROMETHEUS_SERVICEMONITOR=9402
# CI_PIPELINE_SOURCE=push
# CI_RUNNER_VERSION=16.10.0
# FF_RESOLVE_FULL_TLS_CHAIN=false
# GITLAB_KAS_PORT=tcp://10.96.191.81:8150
# GITLAB_KAS_SERVICE_PORT=8150
# GITLAB_POSTGRESQL_METRICS_PORT_9187_TCP=tcp://10.96.253.101:9187
# CI_SERVER_VERSION_MAJOR=16
# CI_BUILDS_DIR=/builds
# CI_DEFAULT_BRANCH=main
# FF_SKIP_NOOP_BUILD_STAGES=true
# FF_USE_FASTZIP=false
# FF_USE_WINDOWS_JOB_OBJECT=false
# GITLAB_PROMETHEUS_SERVER_PORT_80_TCP_PORT=80
# GITLAB_CERTMANAGER_PORT=tcp://10.96.12.220:9402
# GITLAB_CERTMANAGER_SERVICE_PORT=9402
# CI_SERVER_URL=http://gitlab.geniouslab.io
# CI_COMMIT_REF_PROTECTED=true
# CI_TEMPLATE_REGISTRY_HOST=registry.gitlab.com
# GITLAB_REGISTRY_PORT_5000_TCP_ADDR=10.96.13.53
# GITLAB_WEBSERVICE_DEFAULT_PORT_8080_TCP_ADDR=10.96.97.35
# GITLAB_GITLAB_SHELL_SERVICE_PORT_SSH=22
# GITLAB_REDIS_METRICS_SERVICE_PORT=9121
# GITLAB_PROMETHEUS_SERVER_PORT_80_TCP_PROTO=tcp
# GITLAB_REDIS_METRICS_PORT=tcp://10.96.219.146:9121
# GITLAB_WEBSERVICE_DEFAULT_SERVICE_HOST=10.96.97.35
# CI_REGISTRY_IMAGE=registry.gitlab.geniouslab.io/cicd/fastapi
# CI_PROJECT_ID=2
# CI_COMPONENT_FQDN=gitlab.geniouslab.io
# GITLAB_FEATURES=
# GITLAB_KAS_PORT_8150_TCP=tcp://10.96.191.81:8150
# GITLAB_CI=true
# CI_COMMIT_SHA=a45117c057770f08f84f7c4e433b9bae12043bc5
# GITLAB_GITLAB_EXPORTER_PORT=tcp://10.96.236.110:9168
# GITLAB_WEBSERVICE_DEFAULT_PORT_8181_TCP_ADDR=10.96.97.35
# GITLAB_REDIS_METRICS_PORT_9121_TCP=tcp://10.96.219.146:9121
# GITLAB_KAS_PORT_8151_TCP=tcp://10.96.191.81:8151
# GITLAB_GITLAB_EXPORTER_SERVICE_PORT=9168
# FF_RETRIEVE_POD_WARNING_EVENTS=false
# CI_CONCURRENT_ID=0
# GITLAB_WEBSERVICE_DEFAULT_PORT_8080_TCP_PORT=8080
# GITLAB_REDIS_MASTER_SERVICE_PORT=6379
# GITLAB_REGISTRY_PORT_5000_TCP_PORT=5000
# GITLAB_CERTMANAGER_PORT_9402_TCP=tcp://10.96.12.220:9402
# GITLAB_GITLAB_EXPORTER_PORT_9168_TCP_ADDR=10.96.236.110
# GITLAB_REDIS_MASTER_PORT=tcp://10.96.168.122:6379
# GITLAB_WEBSERVICE_DEFAULT_PORT_8083_TCP_ADDR=10.96.97.35
# FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR=false
# FF_USE_DOCKER_AUTOSCALER_DIAL_STDIO=true
# CI_REGISTRY_USER=gitlab-ci-token
# CI_SERVER_PORT=80
# GITLAB_WEBSERVICE_DEFAULT_PORT_8080_TCP_PROTO=tcp
# GITLAB_REGISTRY_PORT_5000_TCP_PROTO=tcp
# GITLAB_MINIO_SVC_PORT_9000_TCP_ADDR=10.96.27.238
# GITLAB_MINIO_SVC_SERVICE_PORT_HTTP=9000
# GITLAB_KAS_PORT_8153_TCP=tcp://10.96.191.81:8153
# CI_PROJECT_PATH=cicd/fastapi
# CI_PROJECT_DIR=/builds/cicd/fastapi
# GITLAB_REDIS_MASTER_PORT_6379_TCP_ADDR=10.96.168.122
# GITLAB_KAS_PORT_8154_TCP=tcp://10.96.191.81:8154
# GITLAB_WEBSERVICE_DEFAULT_PORT_8181_TCP_PORT=8181
# CI_COMMIT_TIMESTAMP=2024-04-27T14:00:20+09:00
# FF_ENABLE_JOB_CLEANUP=false
# CI_PROJECT_NAMESPACE=cicd
# GITLAB_GITLAB_EXPORTER_PORT_9168_TCP_PORT=9168
# GITLAB_WEBSERVICE_DEFAULT_PORT_8083_TCP_PORT=8083
# GITLAB_WEBSERVICE_DEFAULT_PORT_8181_TCP_PROTO=tcp
# CI_NODE_TOTAL=1
# FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL=false
# CI_SERVER_NAME=GitLab
# FF_USE_DIRECT_DOWNLOAD=true
# GITLAB_WEBSERVICE_DEFAULT_PORT=tcp://10.96.97.35:8080
# GITLAB_MINIO_SVC_PORT_9000_TCP_PORT=9000
# GITLAB_WEBSERVICE_DEFAULT_PORT_8083_TCP_PROTO=tcp
# GITLAB_WEBSERVICE_DEFAULT_SERVICE_PORT=8080
# GITLAB_GITLAB_EXPORTER_PORT_9168_TCP_PROTO=tcp
# CI_PROJECT_NAMESPACE_ID=2
# CI_PIPELINE_CREATED_AT=2024-04-27T05:00:22Z
# GITLAB_REDIS_MASTER_PORT_6379_TCP_PORT=6379
# GITLAB_MINIO_SVC_PORT_9000_TCP_PROTO=tcp
# GITLAB_PROMETHEUS_SERVER_PORT_80_TCP=tcp://10.96.199.210:80
# GITLAB_POSTGRESQL_PORT_5432_TCP_ADDR=10.96.80.215
# TERM=xterm
# FF_USE_IMPROVED_URL_MASKING=false
# RUNNER_TEMP_PROJECT_DIR=/builds/cicd/fastapi.tmp
# CI_JOB_NAME_SLUG=job-docker-build
# CI_CONCURRENT_PROJECT_ID=0
# KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
# GITLAB_REDIS_MASTER_PORT_6379_TCP_PROTO=tcp
# CI_PIPELINE_URL=http://gitlab.geniouslab.io/cicd/fastapi/-/pipelines/38
# FF_KUBERNETES_HONOR_ENTRYPOINT=false
# GITLAB_POSTGRESQL_SERVICE_HOST=10.96.80.215
# PATH=/usr/local/bin:/kaniko:/busybox
# CI_RUNNER_DESCRIPTION=gitlab-gitlab-runner-6688667699-zzc48
# CI_JOB_STARTED_AT=2024-04-27T05:01:08Z
# CI_SERVER_VERSION_MINOR=10
# GITLAB_REGISTRY_SERVICE_HOST=10.96.13.53
# GITLAB_GITLAB_SHELL_SERVICE_HOST=10.96.114.103
# GITLAB_POSTGRESQL_PORT_5432_TCP_PORT=5432
# GITLAB_MINIO_SVC_SERVICE_HOST=10.96.27.238
# CI_PROJECT_VISIBILITY=public
# CI_PROJECT_TITLE=fastapi
# CI_COMMIT_TITLE=modified .gitlab-ci.yml
# FF_USE_NEW_BASH_EVAL_STRATEGY=false
# GITLAB_USER_EMAIL=admin@example.com
# GITLAB_REGISTRY_PORT_5000_TCP=tcp://10.96.13.53:5000
# KUBERNETES_PORT_443_TCP_PORT=443
# GITLAB_WEBSERVICE_DEFAULT_PORT_8080_TCP=tcp://10.96.97.35:8080
# GITLAB_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
# SSL_CERT_DIR=/kaniko/ssl/certs
# CI_SERVER=yes
# FF_USE_GIT_BUNDLE_URIS=true
# KUBERNETES_PORT_443_TCP_PROTO=tcp
# CI_PROJECT_REPOSITORY_LANGUAGES=smarty,dockerfile,python
# CI_PAGES_URL=http://cicd.pages.gitlab.geniouslab.io/fastapi
# FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION=false
# GITLAB_WEBSERVICE_DEFAULT_PORT_8181_TCP=tcp://10.96.97.35:8181
# FF_PRINT_POD_EVENTS=false
# FF_SET_PERMISSIONS_BEFORE_CLEANUP=true
# CI_SERVER_FQDN=gitlab.geniouslab.io
# CI_COMMIT_AUTHOR=clownchrys <clownchrys@gmail.com>
# GITLAB_GITLAB_EXPORTER_PORT_9168_TCP=tcp://10.96.236.110:9168
# GITLAB_CERTMANAGER_WEBHOOK_PORT_443_TCP_ADDR=10.96.203.90
# GITLAB_POSTGRESQL_METRICS_SERVICE_PORT_HTTP_METRICS=9187
# GITLAB_PROMETHEUS_SERVER_SERVICE_PORT_HTTP=80
# GITLAB_WEBSERVICE_DEFAULT_PORT_8083_TCP=tcp://10.96.97.35:8083
# CI_JOB_IMAGE=gcr.io/kaniko-project/executor:debug
# CI_RUNNER_SHORT_TOKEN=qLz4ac2Y
# CI_PAGES_DOMAIN=pages.gitlab.geniouslab.io
# GITLAB_MINIO_SVC_PORT_9000_TCP=tcp://10.96.27.238:9000
# GITLAB_KAS_SERVICE_PORT_TCP_KAS_K8S_API=8154
# GITLAB_POSTGRESQL_METRICS_SERVICE_HOST=10.96.253.101
# GITLAB_WEBSERVICE_DEFAULT_SERVICE_PORT_HTTP_WORKHORSE=8181
# CI_PROJECT_CLASSIFICATION_LABEL=
# CI_PIPELINE_NAME=
# CI_COMMIT_BRANCH=main
# CI_JOB_TIMEOUT=3600
# GITLAB_POSTGRESQL_PORT=tcp://10.96.80.215:5432
# GITLAB_POSTGRESQL_SERVICE_PORT=5432
# GITLAB_POSTGRESQL_SERVICE_PORT_TCP_POSTGRESQL=5432
# GITLAB_REDIS_MASTER_PORT_6379_TCP=tcp://10.96.168.122:6379
# GITLAB_KAS_SERVICE_PORT_TCP_KAS_INTERNAL_API=8153
# CI_RUNNER_ID=9
# FF_USE_POWERSHELL_PATH_RESOLVER=false
# CI_API_GRAPHQL_URL=http://gitlab.geniouslab.io/api/graphql
# GITLAB_GITLAB_SHELL_PORT=tcp://10.96.114.103:22
# GITLAB_REGISTRY_PORT=tcp://10.96.13.53:5000
# GITLAB_MINIO_SVC_PORT=tcp://10.96.27.238:9000
# GITLAB_MINIO_SVC_SERVICE_PORT=9000
# GITLAB_GITLAB_SHELL_SERVICE_PORT=22
# GITLAB_REGISTRY_SERVICE_PORT=5000
# GITLAB_CERTMANAGER_WEBHOOK_PORT_443_TCP_PORT=443
# CI_API_V4_URL=http://gitlab.geniouslab.io/api/v4
# GITLAB_USER_NAME=Administrator
# CI_REGISTRY=registry.gitlab.geniouslab.io
# GITLAB_CERTMANAGER_WEBHOOK_PORT_443_TCP_PROTO=tcp
# GITLAB_REDIS_MASTER_SERVICE_PORT_TCP_REDIS=6379
# CI_PIPELINE_IID=30
# GITLAB_GITLAB_SHELL_PORT_22_TCP_ADDR=10.96.114.103
# GITLAB_WEBSERVICE_DEFAULT_SERVICE_PORT_HTTP_WEBSERVICE=8080
# GITLAB_POSTGRESQL_PORT_5432_TCP=tcp://10.96.80.215:5432
# CI_SERVER_SHELL_SSH_HOST=gitlab.geniouslab.io
# FF_USE_POD_ACTIVE_DEADLINE_SECONDS=true
# CI_JOB_URL=http://gitlab.geniouslab.io/cicd/fastapi/-/jobs/103
# FF_USE_ADVANCED_POD_SPEC_CONFIGURATION=false
# CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
# KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
# KUBERNETES_SERVICE_PORT_HTTPS=443
# FF_TEST_FEATURE=false
# FF_USE_INIT_WITH_DOCKER_EXECUTOR=false
# GITLAB_PROMETHEUS_SERVER_SERVICE_HOST=10.96.199.210
# DOCKER_CONFIG=/kaniko/.docker/
# CI_DISPOSABLE_ENVIRONMENT=true
# CI_COMMIT_REF_SLUG=main
# GITLAB_POSTGRESQL_METRICS_PORT=tcp://10.96.253.101:9187
# GITLAB_POSTGRESQL_METRICS_SERVICE_PORT=9187
# KUBERNETES_SERVICE_HOST=10.96.0.1
# GITLAB_GITLAB_SHELL_PORT_22_TCP_PORT=22
# GITLAB_KAS_SERVICE_PORT_TCP_KAS_EXTERNAL_API=8150
# PWD=/workspace
# CI_RUNNER_TAGS=[]
# FF_SECRET_RESOLVING_FAILS_IF_MISSING=true
# FF_USE_NEW_SHELL_ESCAPE=false
# GITLAB_GITLAB_SHELL_PORT_22_TCP_PROTO=tcp
# CI_PROJECT_PATH_SLUG=cicd-fastapi
# CI_PROJECT_URL=http://gitlab.geniouslab.io/cicd/fastapi
# CI_CONFIG_PATH=.gitlab-ci.yml
# CI_COMMIT_BEFORE_SHA=ed3f33cf57b3a2c301f3ba7ffbcdb27b0ba187dd
# CI_PIPELINE_ID=38
# GITLAB_POSTGRESQL_METRICS_PORT_9187_TCP_ADDR=10.96.253.101
# CI_COMMIT_MESSAGE=modified .gitlab-ci.yml

# FF_ENABLE_BASH_EXIT_CODE_CHECK=false
# GITLAB_USER_ID=1
# GITLAB_CERTMANAGER_WEBHOOK_SERVICE_PORT_HTTPS=443
# GITLAB_CERTMANAGER_WEBHOOK_PORT_443_TCP=tcp://10.96.203.90:443
# CI_JOB_STATUS=running
# CI_JOB_NAME=job_docker_build
# CI_SERVER_SHELL_SSH_PORT=22
# GITLAB_KAS_PORT_8150_TCP_ADDR=10.96.191.81
# GITLAB_POSTGRESQL_METRICS_PORT_9187_TCP_PORT=9187