apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: airflow-extras
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5G
#   storageClassName: local-path