apiVersion: metallb.io/v1beta1 
# metalib의 l2모드를 사용한다.
kind: L2Advertisement 
metadata:
  name: l2-network
  # namespace: metallb-system  # L2Advertisement이 사용할 namespace명
spec:
  # 사용할 ipAddressPools을 추가해주는 데 위에 정의한 ipAddressPools을 사용하도록 한다.
  ipAddressPools:
    - ip-pool
