apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-parameters
  namespace: oauth2-proxy
data:
  ALLOW_SELF_SIGNED_ISSUER: "true"
  ENABLE_M2M_TOKENS: "false"
  EXTRA_JWT_ISSUERS: https://kubernetes.default.svc.cluster.local=https://kubernetes.default.svc.cluster.local
  FORCE_HTTPS: "false"