apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: auth
data:
  # https://github.com/dexidp/dex/blob/master/examples/config-ad-kubelogin.yaml
  # https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml
  # https://dexidp.io/docs/connectors/oidc
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    # enablePasswordDB: true
    # staticPasswords:
    # - email: user@example.com
    #   hashFromEnv: DEX_USER_PASSWORD
    #   username: user
    #   userID: "15841185641784"
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/oauth2/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
    connectors:
    - type: oidc
      id: keycloak
      name: Keycloak
      config:
        issuer: https://keycloak.clownchrys.link/realms/default
        clientID: <REDACTED>
        clientSecret: <REDACTED>
        redirectURI: https://kubeflow.geniouslab.io/dex/callback
        basicAuthUnsupported: true
        scopes:
          - profile
          - email
          - groups
          - openid
        insecureSkipEmailVerified: true
        insecureEnableGroups: true
        getUserInfo: true
        # userIDKey: sub
        # userNameKey: name
        # arcValues:
        #   - <value>
        promptType: consent
        # claimMapping:
        #   preferred_username: preferred_username
        #   email: mail
        #   groups: groups
        providerDiscoveryOverrides:
          # tokenURL provides a way to user overwrite the token URL
          # from the .well-known/openid-configuration 'token_endpoint'.
          # tokenURL: ""
          #
          # authURL provides a way to user overwrite the authorization URL
          # from the .well-known/openid-configuration 'authorization_endpoint'.   
          # authURL: ""


