apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: oidc-authservice-parameters
  env: authservice-config.env
  behavior: replace

secretGenerator:
- name: oidc-authservice-client
  env: keycloak-credentials.env
  behavior: replace

# NOTE: WHEN SELF-SIGNED KEYCLOAK
# patches:
# - target:
#     kind: StatefulSet
#     name: oidc-authservice
#   path: statefulset.keycloak.yaml