expose:
  type: ingress
  tls:
    enabled: false
    certSource: auto
    auto:
      commonName: ""
    secret:
      secretName: ""
  ingress:
    hosts:
      core: harbor.geniouslab.io
    controller: default
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-log: "true"
      nginx.ingress.kubernetes.io/rewrite-taget: /
      # nginx.ingress.kubernetes.io/rewrite-target: /v2/proxy/library/$1
      # nginx.ingress.kubernetes.io/configuration-snippet: |
      #   if ( $request_uri ~ "scope=repository%3Alibrary(.*)" ) {
      #     rewrite ^ /service/token?scope=repository%3Aproxy%2Flibrary$1 break;
      #   }
      #   more_set_headers "Request-Id: $req_id";

# harbor.io/PROJECT/REPOSITORY[:TAG]
externalURL: http://harbor.geniouslab.io

existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
harborAdminPassword: admin

database:
  type: external
  external:
    host: postgresql.postgresql.svc
    port: 5432
    username: harbor_service
    password: harbor_service
    coreDatabase: harbor_registry
    # if using existing secret, the key must be "password"
    existingSecret: ""
    # "disable" - No SSL
    # "require" - Always SSL (skip verification)
    # "verify-ca" - Always SSL (verify that the certificate presented by the
    # server was signed by a trusted CA)
    # "verify-full" - Always SSL (verify that the certification presented by the
    # server was signed by a trusted CA and the server host name matches the one
    # in the certificate)
    sslmode: "disable"

redis:
  type: external
  external:
    # support redis, redis+sentinel
    # addr for redis: <host_redis>:<port_redis>
    # addr for redis+sentinel: <host_sentinel1>:<port_sentinel1>,<host_sentinel2>:<port_sentinel2>,<host_sentinel3>:<port_sentinel3>
    addr: redis-master.redis.svc
    # The name of the set of Redis instances to monitor, it must be set to support redis+sentinel
    sentinelMasterSet: ""
    # The "coreDatabaseIndex" must be "0" as the library Harbor
    # used doesn't support configuring it
    # harborDatabaseIndex defaults to "0", but it can be configured to "6", this config is optional
    # cacheLayerDatabaseIndex defaults to "0", but it can be configured to "7", this config is optional
    coreDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    trivyAdapterIndex: "5"
    # harborDatabaseIndex: "6"
    # cacheLayerDatabaseIndex: "7"
    # username field can be an empty string, and it will be authenticated against the default user
    username: ""
    password: redis
    # If using existingSecret, the key must be REDIS_PASSWORD
    existingSecret: ""