apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-network
spec:
  # serviceSelector:
  #   matchLabels:
  #     stage: dev
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
    - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true

# ---
# apiVersion: cilium.io/v2alpha1
# kind: CiliumL2AnnouncementPolicy
# metadata:
#   name: l2-network-2
# spec:
#   serviceSelector:
#     matchExpressions:
#       - {key: stage, operator: In, values: [stg, prd]}
#   nodeSelector:
#     matchExpressions:
#       - key: node-role.kubernetes.io/control-plane
#         operator: DoesNotExist
#   interfaces:
#     - ^eth[0-9]+
#   externalIPs: true
#   loadBalancerIPs: true