# https://github.com/kubeflow/katib/tree/master/examples/v1beta1

---
# https://github.com/kubeflow/katib/blob/master/examples/v1beta1/kubeflow-training-operator/pytorchjob-mnist.yaml
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  # namespace: kubeflow
  name: pytorchjob-mnist # Exp name

# Experiment 관련 메타 정보 작성
spec:
  parallelTrialCount: 1  # 1. 병렬로 실행할 Trial 의 개수
  maxTrialCount: 1  # 2. 최대 Trial 개수 (도달하면 실험 종료 : Succeeded status 로 종료)
  maxFailedTrialCount: 1  # 3. 최대 failed Trial 개수 (도달하면 실험 종료 : Failed status 로 종료)

  # Objective Function
  # 최적화하기 위한 metric, type, early stopping goal 등을 포함
  objective:
    type: minimize
    goal: 0.001

    # Trial 에서 출력할 때, 정해진 형식으로 StdOut 으로 출력하면 name 을 parsing 할 수 있음
    # https://www.kubeflow.org/docs/components/katib/experiment/#metrics-collector

    # objectiveMetricName 은 hp search 를 수행할 objective metric 의 이름
    # addtionalMetricName 은 hp search 와는 관계없지만 함께 출력할 metric 의 이름
    objectiveMetricName: loss
    # additionalMetricNames: ["train-accuracy"]

  # Hyperparameter Search Algorithm
  algorithm:
    # Katib 에서는 현재 지원하고 있는 search algorithm 이 다음과 같이 정해져 있음. 아래 참고
    # https://www.kubeflow.org/docs/components/katib/experiment/#search-algorithms

    # 각각의 algorithm 은 정해진 HP search package 를 사용하여 동작하며,
    # 어떤 docker image 를 사용할 것인지는 katib 설치 당시 배포한 configmap 에 적혀있음
    # 다음 명령을 통해서 어떤 algorithm 이 어떤 package 를 사용하는지 확인할 수 있음
    # 각 algorithm name에 따라 다른 패키지를 사용함
    # `kubectl get configmap katib-config -o yaml` 을 실행후 아래 쪽에 suggestion 필드 확인
    algorithmName: random

  # HP Search 를 수행할 space 정의
  # 각각의 hyperparameter 마다 type 은 무엇인지, space 는 무엇인지를 정의
  # https://github.com/kubeflow/katib/blob/195db292374dcf3b39b55dcb3fcd14b3a55d5942/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L186-L207
  parameters:
    - name: lr  # trialTemplate.trialParameters[x].reference 와 일치해야함. (중요, 실수하기 쉬운 부분)
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: momentum
      parameterType: double
      feasibleSpace:
        min: "0.5"
        max: "0.9"

  # Suggestion 에 의해 생성된 HP 후보 조합 하나를 input 으로 받아서 학습 및 평가를 진행할 Trial 의 템플릿
  # https://www.kubeflow.org/docs/components/katib/user-guides/trial-template/
  trialTemplate:
    retain: true  # trial 완료 시, trial resource 를 정리하지 않음

    # 아래 trialSpec.spec.template.spec.containers[x].name 중에서 metric 을 출력하는 container 의 이름
    # 지금 예시에서는 container 가 하나뿐이므로 해당 container 의 이름으로 출력
    primaryContainerName: pytorch

    # 아래 trialSpec.spec.template.spec.containers[x].command (or args) 에서 사용할 Hyperparameter 에 대한 메타 정보 정의
    # trialParameters[x].name 은 아래 trialSpec 에서의 값과 매핑되며,
    # trialParameters[x].reference 는 위의 parameters[x].name 과 매핑됨(위와 반드시 일치시키기)
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: momentum
        description: Momentum for the training model
        reference: momentum

    # Workerjob에 해당하는 부분

    # https://www.kubeflow.org/docs/components/katib/trial-template/
    # trialSpec 으로는 Job, TfJob 등의 리소스를 사용할 수 있음
    trialSpec:
      apiVersion: kubeflow.org/v1
      kind: PyTorchJob
      spec:
        pytorchReplicaSpecs:
          Master:
            replicas: 1
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  # https://www.kubeflow.org/docs/components/katib/hyperparameter/#example-using-random-search-algorithm
                  # https://github.com/kubeflow/katib/issues/1638
                  # 현재 버전의 katib (v0.17.0 기준) 는 istio sidecar 와 함께 사용할 수 없음 -> istio 관련 에러가 꽤 많이 존재한다고 함
                  # 확인된 사항: 실제 실험이 종료되었음에도 metrics collector가 멈추지 않아 전체 실험이 종료되지 않음
                  sidecar.istio.io/inject: "false"
              spec:
                containers:
                  - name: pytorch
                    # https://github.com/kubeflow/katib/tree/master/examples/v1beta1/trial-images/pytorch-mnist
                    image: docker.io/kubeflowkatib/pytorch-mnist-cpu:latest
                    command:
                      - "python3"
                      - "/opt/pytorch-mnist/mnist.py"
                      - "--epochs=1"
                      - "--batch-size=16"
                      - "--lr=${trialParameters.learningRate}"
                      - "--momentum=${trialParameters.momentum}"
          Worker:
            replicas: 1
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                containers:
                  - name: pytorch
                    image: docker.io/kubeflowkatib/pytorch-mnist-cpu:latest
                    command:
                      - "python3"
                      - "/opt/pytorch-mnist/mnist.py"
                      - "--epochs=1"
                      - "--batch-size=16"
                      - "--lr=${trialParameters.learningRate}"
                      - "--momentum=${trialParameters.momentum}"
