# https://kserve.github.io/website/latest/

---
# ref. https://kserve.github.io/website/latest/get_started/first_isvc/
# ref. https://bongjasee.tistory.com/21
# cat <<EOF > "./iris-input.json"
# {
#   "instances": [
#     [6.8,  2.8,  4.8,  1.4],
#     [6.0,  3.4,  4.5,  1.6]
#   ]
# }
# EOF
# export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
# export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
# export SERVICE_HOSTNAME=$(kubectl get inferenceservice sklearn-iris -n kubeflow-admin-space -o jsonpath='{.status.url}' | cut -d "/" -f 3)
# curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Content-Type: application/json" "http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/sklearn-iris:predict" -d @./iris-input.json
# curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Content-Type: application/json" "http://kubeflow.geniouslab.io/v1/models/sklearn-iris:predict" -d @./iris-input.json
# curl -v -H "Content-Type: application/json" http://sklearn-iris.kserve-test.kubeflow.geniouslab.io/v1/models/sklearn-iris:predict -d @./iris-input.json

apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      args:
        - --enable_docs_url
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
