apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cluster-local
  namespace: keycloak
spec:
  secretName: keycloak-cluster-local-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # to automatically reflect
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system" # restrict namespace (this is very useful, when reflection-auto-enabled is "true")
      # reflector.v1.k8s.emberstack.com/reflects: minio/minio # to manually reflect (annotate this on reflection-target, not for here)
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
    - cluster.local
    organizationalUnits:
    - keycloak.cluster.local
  commonName: keycloak.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.keycloak.svc.cluster.local"
  issuerRef:
    name: cluster-local-issuer
    kind: ClusterIssuer
    group: cert-manager.io