apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-local
  namespace: cert-manager
spec:
  # Secret names are always required.
  # ca.crt: 인증기관의 cert
  # tls.crt: 발급된 cert
  # tls.key: cert 발급시 사용한 개인키
  secretName: cluster-local-tls
  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    # labels:
    #   certficate: cluster-local
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
    - cluster.local
    # organizationalUnits: []
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: cluster.local
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  # At least one of a DNS Name, URI, IP address or otherName is required.
  # dnsNames:
  #   - "*"
  #   - "*.*.svc.cluster.local"
  # uris:
  #   - spiffe://cluster.local/ns/sandbox/sa/example
  # ipAddresses:
  #   - 192.168.0.5
  # # Needs cert-manager 1.14+ and "OtherNames" feature flag
  # otherNames:
  #   # Should only supply oid of ut8 valued types
  #   - oid: 1.3.6.1.4.1.311.20.2.3 # User Principal Name "OID"
  #     utf8Value: upn@example.local
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
  # # keystores allows adding additional output formats. This is an example for reference only.
  # keystores:
  #   pkcs12:
  #     create: true
  #     passwordSecretRef:
  #       name: example-com-tls-keystore
  #       key: password
  #     profile: Modern2023
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-local-issuer
spec:
  ca:
    secretName: cluster-local-tls