apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-parameters
  namespace: oauth2-proxy
data:
  ALLOW_SELF_SIGNED_ISSUER: "true"
  ENABLE_M2M_TOKENS: "false"
  EXTRA_JWT_ISSUERS: https://keycloak.clownchrys.link/realms/default
  FORCE_HTTPS: "false"