apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- resources/requestauthentication.keycloak-jwt.yaml

secretGenerator:
- name: oauth2-proxy
  namespace: oauth2-proxy
  env: patches/keycloak-credentials.env
  behavior: merge

patches:
# - path: patches/deployment.istiod.yaml
# - path: patches/configmap.istio.yaml
- path: patches/configmap.oauth2-proxy.yaml
- path: patches/configmap.oauth2-proxy-params.yaml
#TODO: remove ra/dex-jwt@istio-system