apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- requestauthentication.keycloak-jwt.yaml

secretGenerator:
- name: oauth2-proxy
  namespace: oauth2-proxy
  env: keycloak-credentials.env
  behavior: merge

patches:
- path: configmap.istio.yaml
- path: configmap.oauth2-proxy.yaml
- path: configmap.oauth2-proxy-params.yaml
# - path: virtualservice.centraldashboard.yaml