architecture: standalone

auth:
  enabled: true
  sentinel: true
  password: "redis"

commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""

master:
  count: 1
  service:
    type: ClusterIP
    portNames:
      redis: "tcp-redis"
    ports:
      redis: 6379

replica:
  kind: StatefulSet
  replicaCount: 3

volumePermissions:
  enabled: true