apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# https://www.kubeflow.org/docs/components/spark-operator/overview/

helmCharts:
- name: spark-operator
  namespace: spark-operator
  releaseName: spark-operator
  repo: https://kubeflow.github.io/spark-operator
  valuesInline:
    webhook:
      enable: true
